spring.datasource.url=jdbc:mysql://smart-campus-operations-savinakarunarathne-46ee.j.aivencloud.com:10662/resource_booking_system?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_4uP5RBAjyX4cW45gkM0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect